Update wizard naming to App Control Wizard
MicrosoftDocs/WDAC-Toolkit pull request #409
Opened 2024-10-08 15:27 UTC by jgeurten

Given the recent rebranding of WDAC to Application Control for Business, the Wizard UI has been updated to match the new branding. 

Instances of WDAC have been renamed to Application Control for Business, Application Control, or simply, App Control. 

All UI elements, logs and text have been updated. The package family name and exe/dll binaries still use the WDACWizard naming convention to ensure updates are successful. You can also search Windows Search for WDAC:

![image](https://github.com/user-attachments/assets/bf070086-a8ee-4e42-9c86-460cb2413500)

![image](https://github.com/user-attachments/assets/f6afb942-75d9-4f91-9ac9-132bc47e69e1)

2024-10-08 15:46 UTC, bowerscd-corp requested changes

2024-10-08 15:46 UTC, bowerscd-corp commented on WDAC-Policy-Wizard/app/MSIX/AllowMicrosoft - SingleFormat.xml
> +  <VersionEx>10.0.5.0</VersionEx>
this doesn't look related

2024-10-08 15:46 UTC, bowerscd-corp commented on WDAC-Policy-Wizard/app/MSIX/AppxManifest.xml
> +            Version="2.0.0.0"
version rollback?

2024-10-08 15:46 UTC, bowerscd-corp commented on WDAC-Policy-Wizard/app/MSIX/CreateScannedPolicy.ps1
> +﻿# ScanPath: path to scan
This doesn't look related to the rebranding

2024-10-08 15:46 UTC, bowerscd-corp commented on WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit - SingleFormat.xml
> +  <VersionEx>10.3.0.0</VersionEx>
another different version?

2024-10-08 15:46 UTC, bowerscd-corp commented on WDAC-Policy-Wizard/app/MSIX/DefaultWindows_Audit - SingleFormat.xml
> -    </Rule>
Seems unrelated?

2024-10-08 15:46 UTC, bowerscd-corp commented on WDAC-Policy-Wizard/app/MSIX/WDAC Wizard.deps.json
> +          "runtimepack.Microsoft.Windows.SDK.NET.Ref": "10.0.22621.34"
?

2024-10-17 20:51 UTC, bowerscd-corp approved these changes
runtimepack.Microsoft.Windows.SDK.NET.Ref comment nonwithstanding, LGTM

2024-10-17 20:52 UTC, merged

2024-12-03 19:26 UTC, Obhiao1997 commented
I have the below version of Windows 
Windows 10 22H2
Feature Pack
1000.19060.1000.0
OS build 19045.5131

and I am unable to install WDAC MSIX installer - the file does not open up with install in the dropdown menu rather it opens up but I do not see the install menu - run as administrator option

2024-12-03 19:27 UTC, Obhiao1997 commented
please can you make this work